# This is a basic workflow to help you get started with Actions

name: BEAST-API-DEVELOPMENT-CI

# events but only for the master branch
on:
  push:
    branches: [master]

jobs:     

  setup-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
      env:
        NODE_ENV: development
        BEAST_PORT: ${{secrets.BEAST_PORT_DEV}}
        ELASTIC_NODE: ${{secrets.ELASTIC_NODE_DEV}}
        ELASTIC_USERNAME: ${{secrets.DEV_ELASTIC_USERNAME}}
        ELASTIC_PASSWORD: ${{secrets.DEV_ELASTIC_PASSWORD}}
        GOOGLE_PLACES_URL: ${{secrets.GOOGLE_PLACES_URL}}
        GOOGLE_PLACES_REQUEST_TIMEOUT: ${{secrets.GOOGLE_PLACES_REQUEST_TIMEOUT}}
        GOOGLE_PLACES_API_KEY: ${{secrets.GOOGLE_PLACES_API_KEY}}
        MERCADO_PAGO_URL: ${{secrets.DEV_MERCADO_PAGO_URL}}
        MERCADO_PAGO_REQUEST_TIMEOUT: ${{secrets.MERCADO_PAGO_REQUEST_TIMEOUT}}
        MERCADO_PAGO_ACCESS_TOKEN: ${{secrets.DEV_MERCADO_PAGO_ACCESS_TOKEN}}
      run: |
        echo Setted DEVELOPMENT env variables
      
      - name: Docker Login
        env:
          DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USER}}
          DOCKER_HUB_PASSWORD: ${{secrets.DEV_DOCKER_HUB_PASSWORD}}
        run: |
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

      - name: Build
        run: |
          docker build ../../ -t firedevs/beast-api:1.0.0

      - name: Publish
        run: |
          docker push firedevs/beast-api:1.0.0
          echo build and published done!!
