# This is a basic workflow to help you get started with Actions

name: BEAST-API-DEVELOPMENT-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build and Push Docker Image
      
        env:
          NODE_ENV: development
          BEAST_PORT: ${{secrets.BEAST_PORT_DEV}}
          ELASTIC_NODE: ${{secrets.ELASTIC_NODE_DEV}}
          ELASTIC_USERNAME: ${{secrets.DEV_ELASTIC_USERNAME}}
          ELASTIC_PASSWORD: ${{secrets.DEV_ELASTIC_PASSWORD}}
          GOOGLE_PLACES_URL: ${{secrets.GOOGLE_PLACES_URL}}
          GOOGLE_PLACES_REQUEST_TIMEOUT: ${{secrets.GOOGLE_PLACES_REQUEST_TIMEOUT}}
          GOOGLE_PLACES_API_KEY: ${{secrets.GOOGLE_PLACES_API_KEY}}
          MERCADO_PAGO_URL: ${{secrets.DEV_MERCADO_PAGO_URL}}
          MERCADO_PAGO_REQUEST_TIMEOUT: ${{secrets.MERCADO_PAGO_REQUEST_TIMEOUT}}
          MERCADO_PAGO_ACCESS_TOKEN: ${{secrets.DEV_MERCADO_PAGO_ACCESS_TOKEN}}
       run: |
        echo Set DEVELOPMENT env variables...
