name: Publish to GAE

on:
  push:
    branches:
      - master
    # tags:
    #   - '*'

jobs:
  Publish:
    name: Publishing
    runs-on: ubuntu-latest
    steps:
      - name: Cloning code
        uses: actions/checkout@v2

      - name: Exporting steps variables and create .env for staging
        if: contains(github.ref, 'refs/tags/') == false && github.ref == 'refs/heads/master'
        run: |
          echo "::set-env name=APP_YML::app-staging.yaml"
          echo "::set-env name=GCP_SA_EMAIL::${{ secrets.STAGING_GCP_SA_EMAIL }}"
          echo "::set-env name=GCP_SA_KEY::${{ secrets.STAGING_GCP_SA_KEY }}"
          echo "::set-env name=PROJECT_ID::${{ secrets.STAGING_PROJECT_ID }}"
          echo "${{ secrets.STAGING_ENV_VARS }}" >> .env

      - name: Exporting steps variables and create .env for production
        if: contains(github.ref, 'refs/tags/')
        run: |
          echo "::set-env name=APP_YML::app-production.yaml"
          echo "::set-env name=GCP_SA_EMAIL::${{ secrets.PRODUCTION_GCP_SA_EMAIL }}"
          echo "::set-env name=GCP_SA_KEY::${{ secrets.PRODUCTION_GCP_SA_KEY }}"
          echo "::set-env name=PROJECT_ID::${{ secrets.PRODUCTION_PROJECT_ID }}"
          echo "${{ secrets.PRODUCTION_ENV_VARS }}" >> .env

      - name: Adding to .env github variables
        run: |
          echo ""
          echo "# CI CD"
          echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}" >> .env
          echo "GITHUB_SHA=${GITHUB_SHA}" >> .env

      - name: Initializing Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ env.GCP_SA_EMAIL }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          gae_config_path: ${{ env.APP_YML}}

      - name: Publishing to GAE
        run: |
          # This client-secret.json is converted by GCP_SA_KEY.
          gcloud auth activate-service-account ${{ env.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud -q app deploy ${{ env.APP_YML}} --promote
