name: Publish to GAE

on:
  push:
    branches: [develop]

jobs:
  initalize-publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Export steps variables
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "::set-env name=APP_YML::app-development.yaml"
          echo "::set-env name=ENV_VARS::${{ secrets.DEVELOPMENT_ENV_VARS }}"
          echo "::set-env name=GCP_SA_EMAIL::${{ secrets.DEVELOPMENT_GCP_SA_EMAIL }}"
          echo "::set-env name=GCP_SA_KEY::${{ secrets.DEVELOPMENT_GCP_SA_KEY }}"
          echo "::set-env name=PROJECT_ID::${{ secrets.DEVELOPMENT_PROJECT_ID }}"

      - name: Create .env
        run: |
          echo ${{ env.ENV_VARS }} >> .env
          echo "COMPILATION=${GITHUB_RUN_NUMBER}" >> .env
          echo "GIT_SHA=${GITHUB_SHA}" >> .env

      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ env.GCP_SA_EMAIL }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          gae_config_path: ${{ env.APP_YML}}

      - name: Publish app to Google App Engine
        run: |
          # This client-secret.json is converted by GCP_SA_KEY.
          gcloud auth activate-service-account ${{ env.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ env.PROJECT_ID }}
          gcloud -q app deploy ${{ env.APP_YML}} --promote
